backend:
  name: github
  repo: jmonteg/UOCq
  branch: master
  #base_url: http://netlify-oauth.azurewebsites.net # Path to ext auth provider


media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "estandards"
    label: "Estàndards i convenis"
    folder: "content/estandards"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string", tagname: "h1"}
      - {label: "Descripció", name: "description", widget: "text", required: false}
      - {label: "Descripció ampliada", name: "desc_ampliada", widget: "text", required: false}
      - {label: "Imatge de Background", name: "background", widget: "image", required: false}
      - {label: "Ordre", name: "weight", widget: "number", required: false}
      - {label: "Contingut", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}

